# Generated by Django 5.0.3 on 2024-03-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainQuestions',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('qtype', models.PositiveSmallIntegerField()),
                ('section', models.PositiveSmallIntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
