# Generated by Django 5.0.3 on 2024-03-16 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestions',
            fields=[
                ('sqid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('qtype', models.PositiveSmallIntegerField()),
                ('section', models.PositiveSmallIntegerField()),
                ('branch', models.BooleanField()),
                ('value', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seance.mainquestions')),
            ],
        ),
    ]
