# Generated by Django 5.0.3 on 2024-03-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0002_subquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestions',
            name='branch',
            field=models.BooleanField(default=None),
        ),
    ]
