# Generated by Django 5.0.3 on 2024-03-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0003_alter_subquestions_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subquestions',
            name='branch',
            field=models.IntegerField(),
        ),
    ]
