# Generated by Django 5.0.3 on 2024-03-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0004_alter_subquestions_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seance.mainquestions')),
            ],
        ),
    ]
