# Generated by Django 5.0.3 on 2024-03-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0005_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainquestions',
            name='children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subquestions',
            name='children',
            field=models.BooleanField(default=False),
        ),
    ]
