# Generated by Django 5.0.3 on 2024-03-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0006_mainquestions_children_subquestions_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('qtype', models.PositiveSmallIntegerField()),
                ('section', models.PositiveSmallIntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='answers',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seance.questions'),
        ),
        migrations.DeleteModel(
            name='SubQuestions',
        ),
        migrations.DeleteModel(
            name='MainQuestions',
        ),
    ]
