# Generated by Django 5.0.3 on 2024-03-25 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0013_questions_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('issue', models.TextField()),
                ('action', models.TextField()),
                ('section', models.PositiveSmallIntegerField()),
                ('rquid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seance.questions')),
            ],
        ),
    ]
