# Generated by Django 5.0.3 on 2024-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0015_remove_suggestions_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestions',
            name='rquid',
            field=models.IntegerField(),
        ),
    ]
