# Generated by Django 5.0.3 on 2024-04-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0016_alter_suggestions_rquid'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='risk',
            field=models.TextField(default='Some advice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestions',
            name='sources',
            field=models.TextField(default='Some source'),
            preserve_default=False,
        ),
    ]
