# Generated by Django 5.0.4 on 2024-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0018_questions_dfd'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
